// The ONLY module that knows Patrol exists (plan §1). A framework change
// rewrites this file and the app-side test files, nothing else.
import 'dart:io';

import '../config.dart';
import '../devices/device.dart';
import '../tests/registry.dart';
import '../util/proc.dart';

class ExecutorResult {
  ExecutorResult({
    required this.role,
    required this.passed,
    required this.timedOut,
    required this.aborted,
    required this.exitCode,
    required this.duration,
  });

  final String role;
  final bool passed;
  final bool timedOut;

  /// Killed by the orchestrator (environment failure), not a test verdict.
  final bool aborted;
  final int exitCode;
  final Duration duration;
}

class PatrolExecutor {
  PatrolExecutor(this.config);

  final HarnessConfig config;

  /// Writes `integration_test/test_bundle.dart` once per run, covering every
  /// test in the manifest, and makes every `patrol test` reuse it
  /// (`--no-generate-bundle`).
  ///
  /// Why: `patrol test` normally regenerates that single file from its
  /// `--target`. Two shards building different tests concurrently in the
  /// same app dir therefore overwrite each other's bundle and end up running
  /// the wrong test. Our bundle is identical for every shard; the test to
  /// run is chosen at compile time by the `E2E_TEST_ID` dart-define each
  /// shard already gets, so each build still contains exactly one test.
  /// Without the define (a manual `patrol test`), every test is registered.
  ///
  /// The body mirrors patrol_cli 4.6.1's TestBundler template (pinned).
  void prepareBundle(List<TestSpec> allTests) {
    final appDir = config.resolve(config.appDir);
    // patrol_cli writes and compiles `<patrol.test_directory>/test_bundle.dart`
    // (pubspec `patrol:` section; default `patrol_test`, NOT
    // integration_test). Writing anywhere else is silently ignored.
    final testDir = _patrolTestDirectory(appDir);
    final imports = StringBuffer();
    final groups = StringBuffer();
    for (final t in allTests) {
      final rel = t.target.startsWith('$testDir/')
          ? t.target.substring(testDir.length + 1)
          : '../${t.target}';
      final alias = _alias(rel);
      imports.writeln("import '$rel' as $alias;");
      groups.writeln("  if (_selected.isEmpty || _selected == '${t.name}') {");
      groups.writeln("    group('${alias.replaceAll('__', '.')}', $alias.main);");
      groups.writeln('  }');
    }
    File('$appDir/$testDir/test_bundle.dart')
      ..createSync(recursive: true)
      ..writeAsStringSync('''
// GENERATED by the e2e orchestrator (PatrolExecutor.prepareBundle) — DO NOT
// EDIT, DO NOT COMMIT. Mirrors patrol_cli's test bundle; the group for a
// test is registered only when E2E_TEST_ID selects it (or is unset).
// ignore_for_file: type=lint, invalid_use_of_internal_member

import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';
import 'package:patrol/src/platform/contracts/contracts.dart';
import 'package:test_api/src/backend/invoker.dart';

// START: GENERATED TEST IMPORTS
$imports// END: GENERATED TEST IMPORTS

const _selected = String.fromEnvironment('E2E_TEST_ID');

Future<void> main() async {
  final platformAutomator = PlatformAutomator(
    config: PlatformAutomatorConfig.defaultConfig(),
  );
  await platformAutomator.initialize();
  final binding = PatrolBinding.ensureInitialized(platformAutomator);
  final testExplorationCompleter = Completer<DartGroupEntry>();

  // Explores the group/test hierarchy; must be the first test to run.
  test('patrol_test_explorer', () {
    final topLevelGroup = Invoker.current!.liveTest.groups.first;
    final dartTestGroup = createDartTestGroup(
      topLevelGroup,
      tags: null,
      excludeTags: null,
    );
    testExplorationCompleter.complete(dartTestGroup);
    print('patrol_test_explorer: obtained Dart-side test hierarchy:');
    reportGroupStructure(dartTestGroup);
  });

// START: GENERATED TEST GROUPS
$groups// END: GENERATED TEST GROUPS

  final dartTestGroup = await testExplorationCompleter.future;
  final appService = PatrolAppService(topLevelDartTestGroup: dartTestGroup);
  binding.patrolAppService = appService;
  await runAppService(appService);
  await platformAutomator.markPatrolAppServiceReady();
  await appService.testExecutionCompleted;
}
''');
  }

  /// `patrol.test_directory` from the app's pubspec.yaml (patrol_cli default
  /// `patrol_test`). A tiny hand parser keeps this file free of extra deps.
  static String _patrolTestDirectory(String appDir) {
    final pubspec = File('$appDir/pubspec.yaml');
    if (!pubspec.existsSync()) return 'patrol_test';
    var inPatrol = false;
    for (final line in pubspec.readAsLinesSync()) {
      if (RegExp(r'^patrol:\s*$').hasMatch(line)) {
        inPatrol = true;
        continue;
      }
      if (inPatrol && RegExp(r'^\S').hasMatch(line)) inPatrol = false;
      final m = RegExp(r'^\s+test_directory:\s*(\S+)').firstMatch(line);
      if (inPatrol && m != null) {
        return m.group(1)!.replaceAll(RegExp('["\']'), '');
      }
    }
    return 'patrol_test';
  }

  static String _alias(String relPath) {
    var name = relPath.endsWith('.dart')
        ? relPath.substring(0, relPath.length - 5)
        : relPath;
    while (name.startsWith('../')) {
      name = name.substring(3);
    }
    name = name.replaceAll('/', '__').replaceAll(RegExp('[^a-zA-Z0-9_]'), '_');
    return RegExp('[0-9]').hasMatch(name[0]) ? '_$name' : name;
  }

  /// Runs [spec] for one role on one device; patrol output goes to [testLog].
  ///
  /// [testServerPort] / [appServerPort] are Patrol's two internal
  /// test-runner<->app ports. They MUST be unique per concurrent role: iOS
  /// simulators share the host loopback, so two sessions on Patrol's
  /// defaults (8081/8082) — our two roles, or another project's simulator
  /// run on the same machine — silently connect to each other's apps.
  Future<ExecutorResult> runRole({
    required TestSpec spec,
    required RoleSpec role,
    required DeviceHandle device,
    required String runId,
    required int? backendPort,
    required int syncPort,
    required int testServerPort,
    required int appServerPort,
    required File testLog,
    Map<String, String> extraDefines = const {},
    Set<String> secretDefines = const {},
    Future<void>? abort,
  }) async {
    testLog.parent.createSync(recursive: true);
    final sink = testLog.openWrite();
    final started = DateTime.now();

    final defines = <String, String>{
      'E2E_RUN_ID': runId,
      'E2E_TEST_ID': spec.name,
      'E2E_ROLE': role.role,
      'E2E_PARTIES': '${spec.roles.length}',
      if (backendPort != null)
        'E2E_BACKEND_URL': 'http://${device.loopbackHost}:$backendPort',
      'E2E_SYNC_URL': 'http://${device.loopbackHost}:$syncPort',
      ...extraDefines,
    };

    final command = [
      'patrol',
      'test',
      '--target', spec.target,
      '--device', device.id,
      '--no-generate-bundle', // see prepareBundle
      '--test-server-port', '$testServerPort',
      '--app-server-port', '$appServerPort',
      for (final e in defines.entries) '--dart-define=${e.key}=${e.value}',
    ];
    // Never print secrets (R10 credentials travel only as defines): the
    // command line and every patrol/flutter/gradle line that echoes it get
    // the secret values replaced.
    final secretValues = [
      for (final key in secretDefines)
        if ((defines[key] ?? '').isNotEmpty) defines[key]!,
    ];
    String redact(String line) {
      var out = line;
      for (final v in secretValues) {
        out = out.replaceAll(v, '<redacted>');
      }
      return out;
    }
    sink.writeln('# ${redact(command.join(' '))}');

    final result = await runProc(
      command,
      cwd: config.resolve(config.appDir),
      timeout: config.testTimeout,
      onLine: (l) => sink.writeln(redact(l)),
      abort: abort,
    );
    if (result.aborted) sink.writeln('# aborted by orchestrator');
    if (result.timedOut) {
      sink.writeln('# killed: exceeded test timeout '
          '(${config.testTimeout.inSeconds}s)');
    }
    await sink.flush();
    await sink.close();

    return ExecutorResult(
      role: role.role,
      passed: result.ok,
      timedOut: result.timedOut,
      aborted: result.aborted,
      exitCode: result.exitCode,
      duration: DateTime.now().difference(started),
    );
  }
}
